export const mockData = {
  product: {
    id: 323,
    name: "Baby Sport Shoes",
    slug: "baby-sport-shoes",
    price: 96,
    sku: "654613612-1-1-1",
    stock: 50,
    short_description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    sale_price: 68,
    sale_count: 0,
    ratings: 0,
    reviews: "0",
    is_hot: null,
    is_sale: true,
    is_new: null,
    is_out_of_stock: null,
    release_date: null,
    developer: null,
    publisher: null,
    game_mode: null,
    rated: null,
    until: null,
    product_categories: [
      {
        name: "Babies",
        slug: "babies",
        parent_name: null,
        disabled: true,
        pivot: { product_id: "323", "product-category_id": "50" },
      },
    ],
    product_brands: [],
    product_tags: [],
    large_pictures: [
      {
        width: "800",
        height: "800",
        url: "/uploads/product_16_1_27c032e0ec.jpg",
        pivot: { related_id: "323", upload_file_id: "1642" },
      },
      {
        width: "800",
        height: "800",
        url: "/uploads/product_16_2_7f9575405f.jpg",
        pivot: { related_id: "323", upload_file_id: "1644" },
      },
      {
        width: "800",
        height: "800",
        url: "/uploads/product_16_3_8050d5961f.jpg",
        pivot: { related_id: "323", upload_file_id: "1643" },
      },
    ],
    pictures: [
      {
        width: "300",
        height: "340",
        url: "/uploads/product_16_1_300x340_d499c88efd.jpg",
        pivot: { related_id: "323", upload_file_id: "1648" },
      },
      {
        width: "300",
        height: "340",
        url: "/uploads/product_16_2_300x340_2b2de25664.jpg",
        pivot: { related_id: "323", upload_file_id: "1649" },
      },
      {
        width: "300",
        height: "340",
        url: "/uploads/product_16_3_300x340_9475179c1e.jpg",
        pivot: { related_id: "323", upload_file_id: "1647" },
      },
    ],
    small_pictures: [
      {
        width: "150",
        height: "150",
        url: "/uploads/product_16_1_150x150_847ceac2f2.jpg",
        pivot: { related_id: "323", upload_file_id: "1646" },
      },
      {
        width: "150",
        height: "150",
        url: "/uploads/product_16_2_150x150_42c25a276a.jpg",
        pivot: { related_id: "323", upload_file_id: "1645" },
      },
    ],
    variants: [],
  },
  relatedProducts: [
    {
      id: 326,
      name: "Blue Boy Shoes",
      slug: "blue-boy-shoes",
      price: 100,
      sku: "654613612-1-1",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 68,
      sale_count: 10,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Babies",
          slug: "babies",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "326", "product-category_id": "50" },
        },
        {
          name: "Toys",
          slug: "toys-3",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "326", "product-category_id": "52" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_1_fc0ded50bb.jpg",
          pivot: { related_id: "326", upload_file_id: "1667" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_2_3834176c36.jpg",
          pivot: { related_id: "326", upload_file_id: "1668" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_3_37906c0947.jpg",
          pivot: { related_id: "326", upload_file_id: "1666" },
        },
      ],
      pictures: [
        {
          width: "300",
          height: "340",
          url: "/uploads/product_10_1_300x340_6b596c29b7.jpg",
          pivot: { related_id: "326", upload_file_id: "1671" },
        },
        {
          width: "300",
          height: "340",
          url: "/uploads/product_10_2_300x340_eceac74299.jpg",
          pivot: { related_id: "326", upload_file_id: "1673" },
        },
        {
          width: "300",
          height: "340",
          url: "/uploads/product_10_3_300x340_e4cb46f47e.jpg",
          pivot: { related_id: "326", upload_file_id: "1672" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_10_1_150x150_c828abc984.jpg",
          pivot: { related_id: "326", upload_file_id: "1670" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_10_2_150x150_4b2020e663.jpg",
          pivot: { related_id: "326", upload_file_id: "1669" },
        },
      ],
      variants: [],
    },
    {
      id: 331,
      name: "Pink Baby Spring Shoes",
      slug: "pink-baby-spring-shoes",
      price: 299,
      sku: "654111995-1-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "331", "product-category_id": "53" },
        },
        {
          name: "Trousers",
          slug: "trousers-4",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "331", "product-category_id": "51" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_12_1_8dc1acaf80.jpg",
          pivot: { related_id: "331", upload_file_id: "1699" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_12_2_c1f0590bbd.jpg",
          pivot: { related_id: "331", upload_file_id: "1700" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_12_3_6b527c2770.jpg",
          pivot: { related_id: "331", upload_file_id: "1698" },
        },
      ],
      pictures: [
        {
          width: "300",
          height: "340",
          url: "/uploads/product_12_1_300x340_8c8de00607.jpg",
          pivot: { related_id: "331", upload_file_id: "1704" },
        },
        {
          width: "300",
          height: "340",
          url: "/uploads/product_12_2_300x340_de7e1a899d.jpg",
          pivot: { related_id: "331", upload_file_id: "1705" },
        },
        {
          width: "300",
          height: "340",
          url: "/uploads/product_12_3_300x340_16d3bbd2cf.jpg",
          pivot: { related_id: "331", upload_file_id: "1703" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_1_150x150_5e61865938.jpg",
          pivot: { related_id: "331", upload_file_id: "1702" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_2_150x150_ad021b72b0.jpg",
          pivot: { related_id: "331", upload_file_id: "1701" },
        },
      ],
      variants: [],
    },
    {
      id: 337,
      name: "3-Year Child blue Shirt ",
      slug: "3-year-child-blue-shirt",
      price: 299,
      sku: "854613298",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 4,
      reviews: "1",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "337", "product-category_id": "53" },
        },
        {
          name: "Trousers",
          slug: "trousers-4",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "337", "product-category_id": "51" },
        },
        {
          name: "Shoes",
          slug: "shoes-2",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "337", "product-category_id": "55" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_5_1_b802a1fedb.jpg",
          pivot: { related_id: "337", upload_file_id: "1746" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_5_2_64d8eaef84.jpg",
          pivot: { related_id: "337", upload_file_id: "1748" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_5_3_0167663b9b.jpg",
          pivot: { related_id: "337", upload_file_id: "1747" },
        },
      ],
      pictures: [
        {
          width: "300",
          height: "340",
          url: "/uploads/shop23_product_5_1_300x340_24452ff346.jpg",
          pivot: { related_id: "337", upload_file_id: "1751" },
        },
        {
          width: "300",
          height: "340",
          url: "/uploads/shop23_product_5_2_300x340_bd13f63a85.jpg",
          pivot: { related_id: "337", upload_file_id: "1752" },
        },
        {
          width: "399",
          height: "423",
          url: "/uploads/shop23_product_5_3_300x340_f4ccb6cca1.jpg",
          pivot: { related_id: "337", upload_file_id: "1753" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_5_1_150x150_50c6ea6bfe.jpg",
          pivot: { related_id: "337", upload_file_id: "1749" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_5_2_150x150_7428905425.jpg",
          pivot: { related_id: "337", upload_file_id: "1750" },
        },
      ],
      variants: [],
    },
  ],
  nextProduct: {
    id: 326,
    name: "Blue Boy Shoes",
    slug: "blue-boy-shoes",
    price: 100,
    sku: "654613612-1-1",
    stock: 50,
    short_description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    sale_price: 68,
    sale_count: 10,
    ratings: 0,
    reviews: "0",
    is_hot: null,
    is_sale: true,
    is_new: null,
    is_out_of_stock: null,
    release_date: null,
    developer: null,
    publisher: null,
    game_mode: null,
    rated: null,
    until: null,
    product_categories: [
      {
        name: "Babies",
        slug: "babies",
        parent_name: null,
        disabled: true,
        pivot: { product_id: "326", "product-category_id": "50" },
      },
      {
        name: "Toys",
        slug: "toys-3",
        parent_name: "Babies",
        disabled: true,
        pivot: { product_id: "326", "product-category_id": "52" },
      },
    ],
    product_brands: [],
    product_tags: [],
    large_pictures: [
      {
        width: "800",
        height: "800",
        url: "/uploads/product_10_1_fc0ded50bb.jpg",
        pivot: { related_id: "326", upload_file_id: "1667" },
      },
      {
        width: "800",
        height: "800",
        url: "/uploads/product_10_2_3834176c36.jpg",
        pivot: { related_id: "326", upload_file_id: "1668" },
      },
      {
        width: "800",
        height: "800",
        url: "/uploads/product_10_3_37906c0947.jpg",
        pivot: { related_id: "326", upload_file_id: "1666" },
      },
    ],
    pictures: [
      {
        width: "300",
        height: "340",
        url: "/uploads/product_10_1_300x340_6b596c29b7.jpg",
        pivot: { related_id: "326", upload_file_id: "1671" },
      },
      {
        width: "300",
        height: "340",
        url: "/uploads/product_10_2_300x340_eceac74299.jpg",
        pivot: { related_id: "326", upload_file_id: "1673" },
      },
      {
        width: "300",
        height: "340",
        url: "/uploads/product_10_3_300x340_e4cb46f47e.jpg",
        pivot: { related_id: "326", upload_file_id: "1672" },
      },
    ],
    small_pictures: [
      {
        width: "150",
        height: "150",
        url: "/uploads/product_10_1_150x150_c828abc984.jpg",
        pivot: { related_id: "326", upload_file_id: "1670" },
      },
      {
        width: "150",
        height: "150",
        url: "/uploads/product_10_2_150x150_4b2020e663.jpg",
        pivot: { related_id: "326", upload_file_id: "1669" },
      },
    ],
    variants: [],
  },
  prevProduct: null,
  featuredProducts: [
    {
      id: 324,
      name: "Baby Summer Underclothes",
      slug: "baby-summer-underclothes",
      price: 299,
      sku: "654111995-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 259,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_1_150x150_608ba7046e.jpg",
          pivot: { related_id: "324", upload_file_id: "1654" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_2_150x150_7619a3dbdb.jpg",
          pivot: { related_id: "324", upload_file_id: "1653" },
        },
      ],
      variants: [],
    },
    {
      id: 328,
      name: "Blue Child Overshoes",
      slug: "blue-child-overshoes",
      price: 39,
      sku: "N/A",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 26,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_1_150x150_e80f302d61.jpg",
          pivot: { related_id: "328", upload_file_id: "1686" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_2_150x150_5ef7b17d74.jpg",
          pivot: { related_id: "328", upload_file_id: "1685" },
        },
      ],
      variants: [
        {
          id: 633,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "633" },
        },
        {
          id: 634,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "634" },
        },
        {
          id: 635,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "635" },
        },
        {
          id: 636,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "636" },
        },
        {
          id: 637,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "637" },
        },
      ],
    },
    {
      id: 331,
      name: "Pink Baby Spring Shoes",
      slug: "pink-baby-spring-shoes",
      price: 299,
      sku: "654111995-1-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_1_150x150_5e61865938.jpg",
          pivot: { related_id: "331", upload_file_id: "1702" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_2_150x150_ad021b72b0.jpg",
          pivot: { related_id: "331", upload_file_id: "1701" },
        },
      ],
      variants: [],
    },
  ],
  bestSellingProducts: [
    {
      id: 335,
      name: "Rag baby doll",
      slug: "rag-baby-doll",
      price: 55,
      sku: "15615132",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 30,
      ratings: 4,
      reviews: "1",
      is_hot: null,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_7_1_150x150_d2eced0208.jpg",
          pivot: { related_id: "335", upload_file_id: "1734" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_7_2_150x150_edafa15854.jpg",
          pivot: { related_id: "335", upload_file_id: "1733" },
        },
      ],
      variants: [],
    },
    {
      id: 332,
      name: "Pink Girl Overshoes",
      slug: "pink-girl-overshoes",
      price: 1999,
      sku: "654613612",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 1699,
      sale_count: 28,
      ratings: 4.5,
      reviews: "2",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_14_1_150x150_c4bc158f3d.jpg",
          pivot: { related_id: "332", upload_file_id: "1710" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_14_2_150x150_2847609bdc.jpg",
          pivot: { related_id: "332", upload_file_id: "1709" },
        },
      ],
      variants: [],
    },
    {
      id: 328,
      name: "Blue Child Overshoes",
      slug: "blue-child-overshoes",
      price: 39,
      sku: "N/A",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 26,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_1_150x150_e80f302d61.jpg",
          pivot: { related_id: "328", upload_file_id: "1686" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_2_150x150_5ef7b17d74.jpg",
          pivot: { related_id: "328", upload_file_id: "1685" },
        },
      ],
      variants: [
        {
          id: 633,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "633" },
        },
        {
          id: 634,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "634" },
        },
        {
          id: 635,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "635" },
        },
        {
          id: 636,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "636" },
        },
        {
          id: 637,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "637" },
        },
      ],
    },
  ],
  latestProducts: [
    {
      id: 327,
      name: "Blue Boy Spring Shoes",
      slug: "blue-boy-spring-shoes",
      price: 59,
      sku: "654613612-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 49,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_13_1_150x150_eb6e76ed7c.jpg",
          pivot: { related_id: "327", upload_file_id: "1678" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_13_2_150x150_3507e566af.jpg",
          pivot: { related_id: "327", upload_file_id: "1677" },
        },
      ],
      variants: [],
    },
    {
      id: 330,
      name: "Pink Baby Caps",
      slug: "pink-baby-caps",
      price: 199,
      sku: null,
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 129,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_8_1_150x150_2406984688.jpg",
          pivot: { related_id: "330", upload_file_id: "1694" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_8_2_150x150_0191c3e228.jpg",
          pivot: { related_id: "330", upload_file_id: "1693" },
        },
      ],
      variants: [],
    },
    {
      id: 333,
      name: "Pink Winter Girl Shoes",
      slug: "pink-winter-girl-shoes",
      price: null,
      sku: "PT0003-2",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non.",
      sale_price: null,
      sale_count: 0,
      ratings: 4,
      reviews: "1",
      is_hot: true,
      is_sale: null,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_1_1_150x150_1ab286da45.jpg",
          pivot: { related_id: "333", upload_file_id: "1718" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_1_2_150x150_83197975a1.jpg",
          pivot: { related_id: "333", upload_file_id: "1717" },
        },
      ],
      variants: [
        {
          id: 638,
          price: 111,
          sale_price: null,
          pivot: { product_id: "333", component_id: "638" },
        },
        {
          id: 639,
          price: 101,
          sale_price: null,
          pivot: { product_id: "333", component_id: "639" },
        },
        {
          id: 640,
          price: 108,
          sale_price: null,
          pivot: { product_id: "333", component_id: "640" },
        },
        {
          id: 641,
          price: 105,
          sale_price: null,
          pivot: { product_id: "333", component_id: "641" },
        },
      ],
    },
  ],
  topRatedProducts: [
    {
      id: 329,
      name: "Casual Brown Shoes",
      slug: "casual-brown-shoes",
      price: 108,
      sku: "PT0003-1",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 0,
      ratings: 5,
      reviews: "1",
      is_hot: null,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_15_1_150x150_2a7567c46b.jpg",
          pivot: { related_id: "329", upload_file_id: "1638" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_15_2_150x150_c39e1d202a.jpg",
          pivot: { related_id: "329", upload_file_id: "1637" },
        },
      ],
      variants: [],
    },
    {
      id: 338,
      name: "White Girl Shoes",
      slug: "white-girl-shoes",
      price: 299,
      sku: "654111995-1-1-1",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 5,
      reviews: "1",
      is_hot: null,
      is_sale: null,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_6_1_150x150_337cce37c2.jpg",
          pivot: { related_id: "338", upload_file_id: "1758" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_6_2_150x150_db6975fedd.jpg",
          pivot: { related_id: "338", upload_file_id: "1757" },
        },
      ],
      variants: [],
    },
    {
      id: 332,
      name: "Pink Girl Overshoes",
      slug: "pink-girl-overshoes",
      price: 1999,
      sku: "654613612",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 1699,
      sale_count: 28,
      ratings: 4.5,
      reviews: "2",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_14_1_150x150_c4bc158f3d.jpg",
          pivot: { related_id: "332", upload_file_id: "1710" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_14_2_150x150_2847609bdc.jpg",
          pivot: { related_id: "332", upload_file_id: "1709" },
        },
      ],
      variants: [],
    },
  ],
};
