export const indexData = {
  products: [
    {
      id: 323,
      name: "Baby Sport Shoes",
      slug: "baby-sport-shoes",
      price: 96,
      sku: "654613612-1-1-1",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 68,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Babies",
          slug: "babies",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "323", "product-category_id": "50" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_16_1_27c032e0ec.jpg",
          pivot: { related_id: "323", upload_file_id: "1642" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_16_2_7f9575405f.jpg",
          pivot: { related_id: "323", upload_file_id: "1644" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_16_3_8050d5961f.jpg",
          pivot: { related_id: "323", upload_file_id: "1643" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_16_1_150x150_847ceac2f2.jpg",
          pivot: { related_id: "323", upload_file_id: "1646" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_16_2_150x150_42c25a276a.jpg",
          pivot: { related_id: "323", upload_file_id: "1645" },
        },
      ],
      variants: [],
    },
    {
      id: 324,
      name: "Baby Summer Underclothes",
      slug: "baby-summer-underclothes",
      price: 299,
      sku: "654111995-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 259,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "324", "product-category_id": "53" },
        },
        {
          name: "Dresses",
          slug: "dresses",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "324", "product-category_id": "54" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_4_1_5342d51c27.jpg",
          pivot: { related_id: "324", upload_file_id: "1651" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_4_2_e79bf8d6f9.jpg",
          pivot: { related_id: "324", upload_file_id: "1652" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_4_3_f673052ad5.jpg",
          pivot: { related_id: "324", upload_file_id: "1650" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_1_150x150_608ba7046e.jpg",
          pivot: { related_id: "324", upload_file_id: "1654" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_2_150x150_7619a3dbdb.jpg",
          pivot: { related_id: "324", upload_file_id: "1653" },
        },
      ],
      variants: [],
    },
    {
      id: 325,
      name: "Blue Baby Winter Shoes",
      slug: "blue-baby-winter-shoes",
      price: 199,
      sku: null,
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 129,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Gifts",
          slug: "gifts",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "325", "product-category_id": "48" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_11_1_9119023e5c.jpg",
          pivot: { related_id: "325", upload_file_id: "1660" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_11_2_04caedd2a1.jpg",
          pivot: { related_id: "325", upload_file_id: "1658" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_11_3_192af67f2e.jpg",
          pivot: { related_id: "325", upload_file_id: "1659" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_11_1_150x150_b2e2487d6e.jpg",
          pivot: { related_id: "325", upload_file_id: "1662" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_11_2_150x150_419cb90caa.jpg",
          pivot: { related_id: "325", upload_file_id: "1661" },
        },
      ],
      variants: [],
    },
    {
      id: 326,
      name: "Blue Boy Shoes",
      slug: "blue-boy-shoes",
      price: 100,
      sku: "654613612-1-1",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 68,
      sale_count: 10,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Babies",
          slug: "babies",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "326", "product-category_id": "50" },
        },
        {
          name: "Toys",
          slug: "toys-3",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "326", "product-category_id": "52" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_1_fc0ded50bb.jpg",
          pivot: { related_id: "326", upload_file_id: "1667" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_2_3834176c36.jpg",
          pivot: { related_id: "326", upload_file_id: "1668" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_3_37906c0947.jpg",
          pivot: { related_id: "326", upload_file_id: "1666" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_10_1_150x150_c828abc984.jpg",
          pivot: { related_id: "326", upload_file_id: "1670" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_10_2_150x150_4b2020e663.jpg",
          pivot: { related_id: "326", upload_file_id: "1669" },
        },
      ],
      variants: [],
    },
    {
      id: 327,
      name: "Blue Boy Spring Shoes",
      slug: "blue-boy-spring-shoes",
      price: 59,
      sku: "654613612-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 49,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "327", "product-category_id": "53" },
        },
        {
          name: "Shoes",
          slug: "shoes-2",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "327", "product-category_id": "55" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_13_1_780b2271db.jpg",
          pivot: { related_id: "327", upload_file_id: "1676" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_13_2_e709c35171.jpg",
          pivot: { related_id: "327", upload_file_id: "1674" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_13_3_51a54d1595.jpg",
          pivot: { related_id: "327", upload_file_id: "1675" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_13_1_150x150_eb6e76ed7c.jpg",
          pivot: { related_id: "327", upload_file_id: "1678" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_13_2_150x150_3507e566af.jpg",
          pivot: { related_id: "327", upload_file_id: "1677" },
        },
      ],
      variants: [],
    },
    {
      id: 328,
      name: "Blue Child Overshoes",
      slug: "blue-child-overshoes",
      price: 39,
      sku: "N/A",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 26,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Garden",
          slug: "garden-2",
          parent_name: "Girls",
          disabled: true,
          pivot: { product_id: "328", "product-category_id": "57" },
        },
        {
          name: "Dresses",
          slug: "dresses",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "328", "product-category_id": "54" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_3_1_0b8b5174ff.jpg",
          pivot: { related_id: "328", upload_file_id: "1684" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_3_2_2c87df9aeb.jpg",
          pivot: { related_id: "328", upload_file_id: "1682" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_3_3_94e92934be.jpg",
          pivot: { related_id: "328", upload_file_id: "1683" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_1_150x150_e80f302d61.jpg",
          pivot: { related_id: "328", upload_file_id: "1686" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_2_150x150_5ef7b17d74.jpg",
          pivot: { related_id: "328", upload_file_id: "1685" },
        },
      ],
      variants: [
        {
          id: 633,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "633" },
          size: [
            {
              id: 628,
              size_name: "Extra Large",
              size: "XL",
              pivot: {
                components_variants_variant_id: "633",
                component_id: "628",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 628,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "633",
                component_id: "628",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 634,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "634" },
          size: [
            {
              id: 626,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "634",
                component_id: "626",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 631,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "634",
                component_id: "631",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 635,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "635" },
          size: [
            {
              id: 625,
              size_name: "Small",
              size: "S",
              pivot: {
                components_variants_variant_id: "635",
                component_id: "625",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 629,
              color_name: "blue",
              color: "#11426b",
              pivot: {
                components_variants_variant_id: "635",
                component_id: "629",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 636,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "636" },
          size: [
            {
              id: 624,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "636",
                component_id: "624",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 632,
              color_name: "yellow",
              color: "#eded65",
              pivot: {
                components_variants_variant_id: "636",
                component_id: "632",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 637,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "637" },
          size: [
            {
              id: 627,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "637",
                component_id: "627",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 630,
              color_name: "red",
              color: "#ab6e6e",
              pivot: {
                components_variants_variant_id: "637",
                component_id: "630",
              },
              color_thumbnail: [],
            },
          ],
        },
      ],
    },
    {
      id: 329,
      name: "Casual Brown Shoes",
      slug: "casual-brown-shoes",
      price: 108,
      sku: "PT0003-1",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 0,
      ratings: 5,
      reviews: "1",
      is_hot: null,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Gifts",
          slug: "gifts",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "329", "product-category_id": "48" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_15_1_8d85997d92.jpg",
          pivot: { related_id: "329", upload_file_id: "1635" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_15_2_e6163c764b.jpg",
          pivot: { related_id: "329", upload_file_id: "1636" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_15_3_e2418df7f5.jpg",
          pivot: { related_id: "329", upload_file_id: "1634" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_15_1_150x150_2a7567c46b.jpg",
          pivot: { related_id: "329", upload_file_id: "1638" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_15_2_150x150_c39e1d202a.jpg",
          pivot: { related_id: "329", upload_file_id: "1637" },
        },
      ],
      variants: [],
    },
    {
      id: 330,
      name: "Pink Baby Caps",
      slug: "pink-baby-caps",
      price: 199,
      sku: null,
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 129,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Gifts",
          slug: "gifts",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "330", "product-category_id": "48" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_8_1_b582f0fc8e.jpg",
          pivot: { related_id: "330", upload_file_id: "1691" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_8_2_dfd9dfb071.jpg",
          pivot: { related_id: "330", upload_file_id: "1692" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_8_3_8673749c96.jpg",
          pivot: { related_id: "330", upload_file_id: "1690" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_8_1_150x150_2406984688.jpg",
          pivot: { related_id: "330", upload_file_id: "1694" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_8_2_150x150_0191c3e228.jpg",
          pivot: { related_id: "330", upload_file_id: "1693" },
        },
      ],
      variants: [],
    },
    {
      id: 331,
      name: "Pink Baby Spring Shoes",
      slug: "pink-baby-spring-shoes",
      price: 299,
      sku: "654111995-1-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "331", "product-category_id": "53" },
        },
        {
          name: "Trousers",
          slug: "trousers-4",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "331", "product-category_id": "51" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_12_1_8dc1acaf80.jpg",
          pivot: { related_id: "331", upload_file_id: "1699" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_12_2_c1f0590bbd.jpg",
          pivot: { related_id: "331", upload_file_id: "1700" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_12_3_6b527c2770.jpg",
          pivot: { related_id: "331", upload_file_id: "1698" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_1_150x150_5e61865938.jpg",
          pivot: { related_id: "331", upload_file_id: "1702" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_2_150x150_ad021b72b0.jpg",
          pivot: { related_id: "331", upload_file_id: "1701" },
        },
      ],
      variants: [],
    },
    {
      id: 332,
      name: "Pink Girl Overshoes",
      slug: "pink-girl-overshoes",
      price: 1999,
      sku: "654613612",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 1699,
      sale_count: 28,
      ratings: 4.5,
      reviews: "2",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "332", "product-category_id": "53" },
        },
        {
          name: "Dresses",
          slug: "dresses",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "332", "product-category_id": "54" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_14_1_a51a6cd990.jpg",
          pivot: { related_id: "332", upload_file_id: "1707" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_14_2_be2d854484.jpg",
          pivot: { related_id: "332", upload_file_id: "1708" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_14_3_95c9a6e938.jpg",
          pivot: { related_id: "332", upload_file_id: "1706" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_14_1_150x150_c4bc158f3d.jpg",
          pivot: { related_id: "332", upload_file_id: "1710" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_14_2_150x150_2847609bdc.jpg",
          pivot: { related_id: "332", upload_file_id: "1709" },
        },
      ],
      variants: [],
    },
    {
      id: 333,
      name: "Pink Winter Girl Shoes",
      slug: "pink-winter-girl-shoes",
      price: null,
      sku: "PT0003-2",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non.",
      sale_price: null,
      sale_count: 0,
      ratings: 4,
      reviews: "1",
      is_hot: true,
      is_sale: null,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Girls",
          slug: "girls-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "333", "product-category_id": "81" },
        },
        {
          name: "Garden",
          slug: "garden-2",
          parent_name: "Girls",
          disabled: true,
          pivot: { product_id: "333", "product-category_id": "57" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_1_1_1e20a1e158.jpg",
          pivot: { related_id: "333", upload_file_id: "1715" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_1_2_2dade0f7b1.jpg",
          pivot: { related_id: "333", upload_file_id: "1716" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_1_3_1a03c37362.jpg",
          pivot: { related_id: "333", upload_file_id: "1714" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_1_1_150x150_1ab286da45.jpg",
          pivot: { related_id: "333", upload_file_id: "1718" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_1_2_150x150_83197975a1.jpg",
          pivot: { related_id: "333", upload_file_id: "1717" },
        },
      ],
      variants: [
        {
          id: 638,
          price: 111,
          sale_price: null,
          pivot: { product_id: "333", component_id: "638" },
          size: [
            {
              id: 629,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "638",
                component_id: "629",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 633,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "638",
                component_id: "633",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 639,
          price: 101,
          sale_price: null,
          pivot: { product_id: "333", component_id: "639" },
          size: [
            {
              id: 630,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "639",
                component_id: "630",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 634,
              color_name: "blue",
              color: "#11426b",
              pivot: {
                components_variants_variant_id: "639",
                component_id: "634",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 640,
          price: 108,
          sale_price: null,
          pivot: { product_id: "333", component_id: "640" },
          size: [
            {
              id: 632,
              size_name: "Small",
              size: "S",
              pivot: {
                components_variants_variant_id: "640",
                component_id: "632",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 636,
              color_name: "lightblue",
              color: "#83c2bd",
              pivot: {
                components_variants_variant_id: "640",
                component_id: "636",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 641,
          price: 105,
          sale_price: null,
          pivot: { product_id: "333", component_id: "641" },
          size: [
            {
              id: 631,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "641",
                component_id: "631",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 635,
              color_name: "red",
              color: "#ab6e6e",
              pivot: {
                components_variants_variant_id: "641",
                component_id: "635",
              },
              color_thumbnail: [],
            },
          ],
        },
      ],
    },
    {
      id: 334,
      name: "First Aid Kit for Kids",
      slug: "first-aid-kit-for-kids",
      price: 599,
      sku: "PT0007",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non.",
      sale_price: null,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Girls",
          slug: "girls-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "334", "product-category_id": "81" },
        },
        {
          name: "Garden",
          slug: "garden-2",
          parent_name: "Girls",
          disabled: true,
          pivot: { product_id: "334", "product-category_id": "57" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_2_1_db54860c0f.jpg",
          pivot: { related_id: "334", upload_file_id: "1724" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_2_2_6be395de59.jpg",
          pivot: { related_id: "334", upload_file_id: "1723" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_2_3_c7f6e7befb.jpg",
          pivot: { related_id: "334", upload_file_id: "1722" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_2_1_150x150_ca13b213ad.jpg",
          pivot: { related_id: "334", upload_file_id: "1726" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_2_2_150x150_5ad7f27937.jpg",
          pivot: { related_id: "334", upload_file_id: "1725" },
        },
      ],
      variants: [
        {
          id: 642,
          price: null,
          sale_price: null,
          pivot: { product_id: "334", component_id: "642" },
          size: [
            {
              id: 635,
              size_name: "Extra Large",
              size: "XL",
              pivot: {
                components_variants_variant_id: "642",
                component_id: "635",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 637,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "642",
                component_id: "637",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 645,
          price: null,
          sale_price: null,
          pivot: { product_id: "334", component_id: "645" },
          size: [
            {
              id: 636,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "645",
                component_id: "636",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 639,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "645",
                component_id: "639",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 647,
          price: null,
          sale_price: null,
          pivot: { product_id: "334", component_id: "647" },
          size: [
            {
              id: 637,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "647",
                component_id: "637",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 640,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "647",
                component_id: "640",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 646,
          price: null,
          sale_price: null,
          pivot: { product_id: "334", component_id: "646" },
          size: [
            {
              id: 638,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "646",
                component_id: "638",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 642,
              color_name: "blue",
              color: "#11426b",
              pivot: {
                components_variants_variant_id: "646",
                component_id: "642",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 643,
          price: null,
          sale_price: null,
          pivot: { product_id: "334", component_id: "643" },
          size: [
            {
              id: 634,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "643",
                component_id: "634",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 641,
              color_name: "red",
              color: "#ab6e6e",
              pivot: {
                components_variants_variant_id: "643",
                component_id: "641",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 644,
          price: null,
          sale_price: null,
          pivot: { product_id: "334", component_id: "644" },
          size: [
            {
              id: 633,
              size_name: "Small",
              size: "S",
              pivot: {
                components_variants_variant_id: "644",
                component_id: "633",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 638,
              color_name: "red",
              color: "#ab6e6e",
              pivot: {
                components_variants_variant_id: "644",
                component_id: "638",
              },
              color_thumbnail: [],
            },
          ],
        },
      ],
    },
    {
      id: 335,
      name: "Rag baby doll",
      slug: "rag-baby-doll",
      price: 55,
      sku: "15615132",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 30,
      ratings: 4,
      reviews: "1",
      is_hot: null,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Girls",
          slug: "girls-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "335", "product-category_id": "81" },
        },
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "335", "product-category_id": "53" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_7_1_2e3594bfb2.jpg",
          pivot: { related_id: "335", upload_file_id: "1730" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_7_2_b382553e4a.jpg",
          pivot: { related_id: "335", upload_file_id: "1732" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_7_3_7299aac845.jpg",
          pivot: { related_id: "335", upload_file_id: "1731" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_7_1_150x150_d2eced0208.jpg",
          pivot: { related_id: "335", upload_file_id: "1734" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_7_2_150x150_edafa15854.jpg",
          pivot: { related_id: "335", upload_file_id: "1733" },
        },
      ],
      variants: [],
    },
    {
      id: 336,
      name: "Red baby shoes",
      slug: "red-baby-shoes",
      price: null,
      sku: "PT0003",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: null,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Gifts",
          slug: "gifts",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "336", "product-category_id": "48" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_9_1_e6dc6fe2ba.jpg",
          pivot: { related_id: "336", upload_file_id: "1740" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_9_2_1a0003f4f6.jpg",
          pivot: { related_id: "336", upload_file_id: "1739" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_9_3_7142022fed.jpg",
          pivot: { related_id: "336", upload_file_id: "1738" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_9_1_150x150_1a7836dce5.jpg",
          pivot: { related_id: "336", upload_file_id: "1745" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_9_2_150x150_7036d98627.jpg",
          pivot: { related_id: "336", upload_file_id: "1744" },
        },
      ],
      variants: [
        {
          id: 648,
          price: 101,
          sale_price: null,
          pivot: { product_id: "336", component_id: "648" },
          size: [
            {
              id: 640,
              size_name: "Extra Large",
              size: "XL",
              pivot: {
                components_variants_variant_id: "648",
                component_id: "640",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 643,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "648",
                component_id: "643",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 650,
          price: 108,
          sale_price: null,
          pivot: { product_id: "336", component_id: "650" },
          size: [
            {
              id: 639,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "650",
                component_id: "639",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 645,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "650",
                component_id: "645",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 649,
          price: 111,
          sale_price: null,
          pivot: { product_id: "336", component_id: "649" },
          size: [
            {
              id: 641,
              size_name: "Small",
              size: "S",
              pivot: {
                components_variants_variant_id: "649",
                component_id: "641",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 644,
              color_name: "red",
              color: "#ab6e6e",
              pivot: {
                components_variants_variant_id: "649",
                component_id: "644",
              },
              color_thumbnail: [],
            },
          ],
        },
      ],
    },
    {
      id: 337,
      name: "3-Year Child blue Shirt ",
      slug: "3-year-child-blue-shirt",
      price: 299,
      sku: "854613298",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 4,
      reviews: "1",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "337", "product-category_id": "53" },
        },
        {
          name: "Trousers",
          slug: "trousers-4",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "337", "product-category_id": "51" },
        },
        {
          name: "Shoes",
          slug: "shoes-2",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "337", "product-category_id": "55" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_5_1_b802a1fedb.jpg",
          pivot: { related_id: "337", upload_file_id: "1746" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_5_2_64d8eaef84.jpg",
          pivot: { related_id: "337", upload_file_id: "1748" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_5_3_0167663b9b.jpg",
          pivot: { related_id: "337", upload_file_id: "1747" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_5_1_150x150_50c6ea6bfe.jpg",
          pivot: { related_id: "337", upload_file_id: "1749" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_5_2_150x150_7428905425.jpg",
          pivot: { related_id: "337", upload_file_id: "1750" },
        },
      ],
      variants: [],
    },
    {
      id: 338,
      name: "White Girl Shoes",
      slug: "white-girl-shoes",
      price: 299,
      sku: "654111995-1-1-1",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 5,
      reviews: "1",
      is_hot: null,
      is_sale: null,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "338", "product-category_id": "53" },
        },
        {
          name: "Toys",
          slug: "toys-4",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "338", "product-category_id": "56" },
        },
        {
          name: "Garden",
          slug: "garden-2",
          parent_name: "Girls",
          disabled: true,
          pivot: { product_id: "338", "product-category_id": "57" },
        },
      ],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_6_1_a63a3293e9.jpg",
          pivot: { related_id: "338", upload_file_id: "1754" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_6_2_b20a9f63ee.jpg",
          pivot: { related_id: "338", upload_file_id: "1756" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_6_3_08996b32b3.jpg",
          pivot: { related_id: "338", upload_file_id: "1755" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_6_1_150x150_337cce37c2.jpg",
          pivot: { related_id: "338", upload_file_id: "1758" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_6_2_150x150_db6975fedd.jpg",
          pivot: { related_id: "338", upload_file_id: "1757" },
        },
      ],
      variants: [],
    },
  ],
  posts: [],
};
