export const shopData = {
  totalCount: 16,
  products: [
    {
      id: 323,
      name: "Baby Sport Shoes",
      slug: "baby-sport-shoes",
      price: 96,
      sku: "654613612-1-1-1",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 68,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Babies",
          slug: "babies",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "323", "product-category_id": "50" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_16_1_27c032e0ec.jpg",
          pivot: { related_id: "323", upload_file_id: "1642" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_16_2_7f9575405f.jpg",
          pivot: { related_id: "323", upload_file_id: "1644" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_16_3_8050d5961f.jpg",
          pivot: { related_id: "323", upload_file_id: "1643" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_16_1_150x150_847ceac2f2.jpg",
          pivot: { related_id: "323", upload_file_id: "1646" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_16_2_150x150_42c25a276a.jpg",
          pivot: { related_id: "323", upload_file_id: "1645" },
        },
      ],
      variants: [],
    },
    {
      id: 324,
      name: "Baby Summer Underclothes",
      slug: "baby-summer-underclothes",
      price: 299,
      sku: "654111995-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 259,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "324", "product-category_id": "53" },
        },
        {
          name: "Dresses",
          slug: "dresses",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "324", "product-category_id": "54" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_4_1_5342d51c27.jpg",
          pivot: { related_id: "324", upload_file_id: "1651" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_4_2_e79bf8d6f9.jpg",
          pivot: { related_id: "324", upload_file_id: "1652" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_4_3_f673052ad5.jpg",
          pivot: { related_id: "324", upload_file_id: "1650" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_1_150x150_608ba7046e.jpg",
          pivot: { related_id: "324", upload_file_id: "1654" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_2_150x150_7619a3dbdb.jpg",
          pivot: { related_id: "324", upload_file_id: "1653" },
        },
      ],
      variants: [],
    },
    {
      id: 325,
      name: "Blue Baby Winter Shoes",
      slug: "blue-baby-winter-shoes",
      price: 199,
      sku: null,
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 129,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Gifts",
          slug: "gifts",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "325", "product-category_id": "48" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_11_1_9119023e5c.jpg",
          pivot: { related_id: "325", upload_file_id: "1660" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_11_2_04caedd2a1.jpg",
          pivot: { related_id: "325", upload_file_id: "1658" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_11_3_192af67f2e.jpg",
          pivot: { related_id: "325", upload_file_id: "1659" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_11_1_150x150_b2e2487d6e.jpg",
          pivot: { related_id: "325", upload_file_id: "1662" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_11_2_150x150_419cb90caa.jpg",
          pivot: { related_id: "325", upload_file_id: "1661" },
        },
      ],
      variants: [],
    },
    {
      id: 326,
      name: "Blue Boy Shoes",
      slug: "blue-boy-shoes",
      price: 100,
      sku: "654613612-1-1",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 68,
      sale_count: 10,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Babies",
          slug: "babies",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "326", "product-category_id": "50" },
        },
        {
          name: "Toys",
          slug: "toys-3",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "326", "product-category_id": "52" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_1_fc0ded50bb.jpg",
          pivot: { related_id: "326", upload_file_id: "1667" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_2_3834176c36.jpg",
          pivot: { related_id: "326", upload_file_id: "1668" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_10_3_37906c0947.jpg",
          pivot: { related_id: "326", upload_file_id: "1666" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_10_1_150x150_c828abc984.jpg",
          pivot: { related_id: "326", upload_file_id: "1670" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_10_2_150x150_4b2020e663.jpg",
          pivot: { related_id: "326", upload_file_id: "1669" },
        },
      ],
      variants: [],
    },
    {
      id: 327,
      name: "Blue Boy Spring Shoes",
      slug: "blue-boy-spring-shoes",
      price: 59,
      sku: "654613612-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 49,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "327", "product-category_id": "53" },
        },
        {
          name: "Shoes",
          slug: "shoes-2",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "327", "product-category_id": "55" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_13_1_780b2271db.jpg",
          pivot: { related_id: "327", upload_file_id: "1676" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_13_2_e709c35171.jpg",
          pivot: { related_id: "327", upload_file_id: "1674" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_13_3_51a54d1595.jpg",
          pivot: { related_id: "327", upload_file_id: "1675" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_13_1_150x150_eb6e76ed7c.jpg",
          pivot: { related_id: "327", upload_file_id: "1678" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_13_2_150x150_3507e566af.jpg",
          pivot: { related_id: "327", upload_file_id: "1677" },
        },
      ],
      variants: [],
    },
    {
      id: 328,
      name: "Blue Child Overshoes",
      slug: "blue-child-overshoes",
      price: 39,
      sku: "N/A",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 26,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Garden",
          slug: "garden-2",
          parent_name: "Girls",
          disabled: true,
          pivot: { product_id: "328", "product-category_id": "57" },
        },
        {
          name: "Dresses",
          slug: "dresses",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "328", "product-category_id": "54" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_3_1_0b8b5174ff.jpg",
          pivot: { related_id: "328", upload_file_id: "1684" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_3_2_2c87df9aeb.jpg",
          pivot: { related_id: "328", upload_file_id: "1682" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_3_3_94e92934be.jpg",
          pivot: { related_id: "328", upload_file_id: "1683" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_1_150x150_e80f302d61.jpg",
          pivot: { related_id: "328", upload_file_id: "1686" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_2_150x150_5ef7b17d74.jpg",
          pivot: { related_id: "328", upload_file_id: "1685" },
        },
      ],
      variants: [
        {
          id: 633,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "633" },
          size: [
            {
              id: 628,
              size_name: "Extra Large",
              size: "XL",
              pivot: {
                components_variants_variant_id: "633",
                component_id: "628",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 628,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "633",
                component_id: "628",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 634,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "634" },
          size: [
            {
              id: 626,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "634",
                component_id: "626",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 631,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "634",
                component_id: "631",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 635,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "635" },
          size: [
            {
              id: 625,
              size_name: "Small",
              size: "S",
              pivot: {
                components_variants_variant_id: "635",
                component_id: "625",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 629,
              color_name: "blue",
              color: "#11426b",
              pivot: {
                components_variants_variant_id: "635",
                component_id: "629",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 636,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "636" },
          size: [
            {
              id: 624,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "636",
                component_id: "624",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 632,
              color_name: "yellow",
              color: "#eded65",
              pivot: {
                components_variants_variant_id: "636",
                component_id: "632",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 637,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "637" },
          size: [
            {
              id: 627,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "637",
                component_id: "627",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 630,
              color_name: "red",
              color: "#ab6e6e",
              pivot: {
                components_variants_variant_id: "637",
                component_id: "630",
              },
              color_thumbnail: [],
            },
          ],
        },
      ],
    },
    {
      id: 329,
      name: "Casual Brown Shoes",
      slug: "casual-brown-shoes",
      price: 108,
      sku: "PT0003-1",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 0,
      ratings: 5,
      reviews: "1",
      is_hot: null,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Gifts",
          slug: "gifts",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "329", "product-category_id": "48" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/product_15_1_8d85997d92.jpg",
          pivot: { related_id: "329", upload_file_id: "1635" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_15_2_e6163c764b.jpg",
          pivot: { related_id: "329", upload_file_id: "1636" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/product_15_3_e2418df7f5.jpg",
          pivot: { related_id: "329", upload_file_id: "1634" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_15_1_150x150_2a7567c46b.jpg",
          pivot: { related_id: "329", upload_file_id: "1638" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_15_2_150x150_c39e1d202a.jpg",
          pivot: { related_id: "329", upload_file_id: "1637" },
        },
      ],
      variants: [],
    },
    {
      id: 330,
      name: "Pink Baby Caps",
      slug: "pink-baby-caps",
      price: 199,
      sku: null,
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 129,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: null,
      is_sale: true,
      is_new: true,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Gifts",
          slug: "gifts",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "330", "product-category_id": "48" },
        },
      ],
      product_brands: [],
      product_tags: [],
      large_pictures: [
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_8_1_b582f0fc8e.jpg",
          pivot: { related_id: "330", upload_file_id: "1691" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_8_2_dfd9dfb071.jpg",
          pivot: { related_id: "330", upload_file_id: "1692" },
        },
        {
          width: "800",
          height: "800",
          url: "/uploads/shop23_product_8_3_8673749c96.jpg",
          pivot: { related_id: "330", upload_file_id: "1690" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_8_1_150x150_2406984688.jpg",
          pivot: { related_id: "330", upload_file_id: "1694" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_8_2_150x150_0191c3e228.jpg",
          pivot: { related_id: "330", upload_file_id: "1693" },
        },
      ],
      variants: [],
    },
  ],
};
