export const sidebarShop = {
  sidebarList: [
    {
      id: 50,
      name: "Babies",
      parent_name: null,
      demoes: "demo23",
      slug: "babies",
      created_by: "1",
      updated_by: "1",
      created_at: "2003-04-22T04:25:03.000000Z",
      updated_at: "2000-10-05T23:17:23.000000Z",
      products_count: "2",
      counts: 4,
      children: [
        {
          id: 52,
          name: "Toys",
          parent_name: "Babies",
          demoes: "demo23",
          slug: "toys-3",
          created_by: "1",
          updated_by: "1",
          created_at: "2003-04-22T11:11:44.000000Z",
          updated_at: "2000-10-06T19:43:53.000000Z",
          products_count: "1",
          counts: "1",
          disabled: true,
        },
        {
          id: 51,
          name: "Trousers",
          parent_name: "Babies",
          demoes: "demo23",
          slug: "trousers-4",
          created_by: "1",
          updated_by: "1",
          created_at: "2003-04-22T08:46:12.000000Z",
          updated_at: "2000-12-30T19:44:22.000000Z",
          products_count: "2",
          counts: "2",
          disabled: true,
        },
      ],
      disabled: true,
    },
    {
      id: 53,
      name: "Boys",
      parent_name: null,
      demoes: "demo23,demo37",
      slug: "boys-2",
      created_by: "1",
      updated_by: "1",
      created_at: "2003-04-22T20:44:14.000000Z",
      updated_at: "2006-06-04T09:16:12.000000Z",
      products_count: "9",
      counts: 8,
      children: [
        {
          id: 54,
          name: "Dresses",
          parent_name: "Boys",
          demoes: "demo23",
          slug: "dresses",
          created_by: "1",
          updated_by: "1",
          created_at: "2003-04-23T00:13:27.000000Z",
          updated_at: "2000-12-20T00:39:52.000000Z",
          products_count: "3",
          counts: "3",
          disabled: true,
        },
        {
          id: 55,
          name: "Shoes",
          parent_name: "Boys",
          demoes: "demo23",
          slug: "shoes-2",
          created_by: "1",
          updated_by: "1",
          created_at: "2003-04-23T03:23:12.000000Z",
          updated_at: "2000-12-30T23:46:02.000000Z",
          products_count: "2",
          counts: "2",
          disabled: true,
        },
        {
          id: 56,
          name: "Toys",
          parent_name: "Boys",
          demoes: "demo23",
          slug: "toys-4",
          created_by: "1",
          updated_by: "1",
          created_at: "2003-04-23T07:12:02.000000Z",
          updated_at: "2001-01-01T17:50:28.000000Z",
          products_count: "1",
          counts: "1",
          disabled: true,
        },
      ],
      disabled: true,
    },
    {
      id: 48,
      name: "Gifts",
      parent_name: null,
      demoes: "demo21,demo22,demo23",
      slug: "gifts",
      created_by: "1",
      updated_by: "1",
      created_at: "2003-04-19T13:21:52.000000Z",
      updated_at: "2009-10-16T10:39:43.000000Z",
      products_count: "17",
      counts: 4,
      category: [],
      disabled: true,
    },
    {
      id: 81,
      name: "Girls",
      parent_name: null,
      demoes: "demo23,demo37",
      slug: "girls-2",
      created_by: "1",
      updated_by: "1",
      created_at: "2003-06-26T21:07:47.000000Z",
      updated_at: "2006-02-17T22:20:28.000000Z",
      products_count: "5",
      counts: 5,
      children: [
        {
          id: 57,
          name: "Garden",
          parent_name: "Girls",
          demoes: "demo23",
          slug: "garden-2",
          created_by: "1",
          updated_by: "1",
          created_at: "2003-04-23T10:40:32.000000Z",
          updated_at: "2001-01-02T10:51:58.000000Z",
          products_count: "4",
          counts: "4",
          disabled: true,
        },
      ],
      disabled: true,
    },
  ],
  featuredProducts: [
    {
      id: 324,
      name: "Baby Summer Underclothes",
      slug: "baby-summer-underclothes",
      price: 299,
      sku: "654111995-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: 259,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: true,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "324", "product-category_id": "53" },
        },
        {
          name: "Dresses",
          slug: "dresses",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "324", "product-category_id": "54" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_1_150x150_608ba7046e.jpg",
          pivot: { related_id: "324", upload_file_id: "1654" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_4_2_150x150_7619a3dbdb.jpg",
          pivot: { related_id: "324", upload_file_id: "1653" },
        },
      ],
      variants: [],
    },
    {
      id: 328,
      name: "Blue Child Overshoes",
      slug: "blue-child-overshoes",
      price: 39,
      sku: "N/A",
      stock: 50,
      short_description:
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      sale_price: null,
      sale_count: 26,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Garden",
          slug: "garden-2",
          parent_name: "Girls",
          disabled: true,
          pivot: { product_id: "328", "product-category_id": "57" },
        },
        {
          name: "Dresses",
          slug: "dresses",
          parent_name: "Boys",
          disabled: true,
          pivot: { product_id: "328", "product-category_id": "54" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_1_150x150_e80f302d61.jpg",
          pivot: { related_id: "328", upload_file_id: "1686" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/shop23_product_3_2_150x150_5ef7b17d74.jpg",
          pivot: { related_id: "328", upload_file_id: "1685" },
        },
      ],
      variants: [
        {
          id: 633,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "633" },
          size: [
            {
              id: 628,
              size_name: "Extra Large",
              size: "XL",
              pivot: {
                components_variants_variant_id: "633",
                component_id: "628",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 628,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "633",
                component_id: "628",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 634,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "634" },
          size: [
            {
              id: 626,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "634",
                component_id: "626",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 631,
              color_name: "black",
              color: "#000000",
              pivot: {
                components_variants_variant_id: "634",
                component_id: "631",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 635,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "635" },
          size: [
            {
              id: 625,
              size_name: "Small",
              size: "S",
              pivot: {
                components_variants_variant_id: "635",
                component_id: "625",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 629,
              color_name: "blue",
              color: "#11426b",
              pivot: {
                components_variants_variant_id: "635",
                component_id: "629",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 636,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "636" },
          size: [
            {
              id: 624,
              size_name: "Large",
              size: "L",
              pivot: {
                components_variants_variant_id: "636",
                component_id: "624",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 632,
              color_name: "yellow",
              color: "#eded65",
              pivot: {
                components_variants_variant_id: "636",
                component_id: "632",
              },
              color_thumbnail: [],
            },
          ],
        },
        {
          id: 637,
          price: null,
          sale_price: null,
          pivot: { product_id: "328", component_id: "637" },
          size: [
            {
              id: 627,
              size_name: "Medium",
              size: "M",
              pivot: {
                components_variants_variant_id: "637",
                component_id: "627",
              },
              size_thumbnail: [],
            },
          ],
          colors: [
            {
              id: 630,
              color_name: "red",
              color: "#ab6e6e",
              pivot: {
                components_variants_variant_id: "637",
                component_id: "630",
              },
              color_thumbnail: [],
            },
          ],
        },
      ],
    },
    {
      id: 331,
      name: "Pink Baby Spring Shoes",
      slug: "pink-baby-spring-shoes",
      price: 299,
      sku: "654111995-1-1-2",
      stock: 50,
      short_description:
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
      sale_price: null,
      sale_count: 0,
      ratings: 0,
      reviews: "0",
      is_hot: true,
      is_sale: null,
      is_new: null,
      is_out_of_stock: null,
      release_date: null,
      developer: null,
      publisher: null,
      game_mode: null,
      rated: null,
      until: null,
      product_categories: [
        {
          name: "Boys",
          slug: "boys-2",
          parent_name: null,
          disabled: true,
          pivot: { product_id: "331", "product-category_id": "53" },
        },
        {
          name: "Trousers",
          slug: "trousers-4",
          parent_name: "Babies",
          disabled: true,
          pivot: { product_id: "331", "product-category_id": "51" },
        },
      ],
      small_pictures: [
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_1_150x150_5e61865938.jpg",
          pivot: { related_id: "331", upload_file_id: "1702" },
        },
        {
          width: "150",
          height: "150",
          url: "/uploads/product_12_2_150x150_ad021b72b0.jpg",
          pivot: { related_id: "331", upload_file_id: "1701" },
        },
      ],
      variants: [],
    },
  ],
};
